### PR TITLE
Upgraded to SonarQube 7.9

### PR DESCRIPTION
**Pull request by kkaarrss**
build on https://github.com/mstoecklmayr/sonar-build-breaker/tree/sonar-7.3

### CODE REVIEW

**Comment by kkaarrss** [comment]
[sonar-build-breaker-plugin-2.3-SNAPSHOT.zip](https://github.com/SonarQubeCommunity/sonar-build-breaker/files/3408476/sonar-build-breaker-plugin-2.3-SNAPSHOT.zip)
And the jar. Tested locally with SonarQube 7.9.

**Comment by frankyjquintero** [comment]
The plugin works perfectly with version 7.9 of sonar and teamcity 2019.1.2

**Comment by sandro-h** [comment]
Hey @kkaarrss, thanks for your work! As you mentioned yourself in #44, some of it doesn't fit so well with Sonarqube 7.9:
- The Issue Severity Breaker doesn't make sense anymore, because preview analysis was dropped in 7.x. The `AnalysisMode` class for example is deprecated, and most likely the severity breaker code has no effect at all since `shouldExecuteOnProject` never evaluates to `true` (did not test it either).
- According to the Sonarqube 7.9 [Supported Platform](https://docs.sonarqube.org/7.9/requirements/requirements/) requirements, we shouldn't use JDK 9 just yet (or at least we should target Java 8), because the plugin is used during analysis.

Right now I'm leaning towards using the changes from https://github.com/adnovum/sonar-build-breaker/commits, which are more minimalistic. I still need to verify that against Sonarqube 7.9 though (it targets 7.7.). From there we can extend and update the codebase and dependencies as necessary.
Full disclosure: that fork was done by a colleague at my employer. If you disagree with this course and think there are valuable improvements here we should take up, do let me know.

**Comment by sandro-h** [comment]
We now released a 2.3.0 version that's compatible with SonarQube 7.9. Thanks again for your work.

**Pull request closed without merging**
