### PR TITLE
Change codes to make plugin compatible with Sonar 7.3

### PR DESCRIPTION
**Pull request by armsargis**
Hi, here is PR for #38

### CODE REVIEW

**Comment by caiconkhicon** [comment]
Hi @armsargis, I see the build was failed. When will it be fixed? 
I am waiting for using sonar-build-breaker with SonarQube 7.3

**Comment by armsargis** [comment]
Buld failed because

```
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

I cannot fix is and should be checked in travis, its not because of code

**Comment by caiconkhicon** [comment]
So you mean it worked for you already? I tried to rebuild it from my local machine, but it failed with this error. Do you have any idea on it?

`[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check (enforce-java-api-compatibility) on project sonar-build-breaker-plugin: Execution enforce-java-api-compatibility of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check failed. IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check (enforce-java-api-compatibility) on project sonar-build-breaker-plugin: Execution enforce-java-api-compatibility of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check failed.`

**Comment by armsargis** [comment]
Try with Java 8

**Comment by armsargis** [comment]
It works for me and deployed in our server

**Comment by armsargis** [comment]
```
mvn clean package
.....

[INFO] -------------------------------------------------------
[INFO] Building jar: /home/sargis/source/sonar-build-breaker/target/sonar-build-breaker-plugin-2.3-SNAPSHOT.jar
[INFO]  already added, skipping
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.713 s
[INFO] Finished at: 2018-09-11T17:31:52+04:00
[INFO] ------------------------------------------------------------------------
 sargis@sargis  ~/source/sonar-build-breaker   master  git status                                                                                                  ✓  1.30 L  0.94G RAM  10021  17:31:52 
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
 sargis@sargis  ~/source/sonar-build-breaker   master  java -version                                                                                               ✓  0.94 L  0.87G RAM  10022  17:32:27 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

```

**Comment by caiconkhicon** [comment]
@armsargis : thanks so much, it works for me now 👍 When will the PR be merged?

**Comment by seenusankara** [comment]
Thanks @armsargis , The new changes are working perfectly 💯

**Comment by sandro-h** [comment]
Hey @armsargis, in the meantime we took over maintainership and just released a version that's compatible with SonarQube 7.3 - 7.9. Thanks for your work nonetheless!

**Pull request closed without merging**
